### ISSUE TITLE
Вывод пробитого чека на экран

### ISSUE THREAD

**Issue by GitMadlab** [andrei-karpov/KSOFT_EmulatorKKT#1]
Добрый день.
Не выводиться пробитый Чек и XML.
Кассовый чек пробивается без ошибок.

Платформа: 1С:Предприятие 8.3 (8.3.18.1289)
Конфигурация: Управление торговлей, редакция 11 (11.4.13.275)

Расширения конфигурации:
- KSOFT: Эмулятор ККТ (1.0.0.8)

Режим: Файловый (без сжатия)
Приложение: Тонкий клиент
Локализация: Информационная база: русский (Россия), Сеанс: русский
Вариант интерфейса: Такси

**Comment by andrei-karpov** [comment]
Здравствуйте, поставьте в настройках открытие формы независимо

**Comment by GitMadlab** [comment]
Спасибо.
Простите меня великодушно. Это я слепой и не внимательный.
